### ISSUE TITLE
Automatic device detection

### ISSUE THREAD

**Issue by traverseda** [nsensfel/relabsd#3]
I'd like to set up relabsd as a proper daemon, doing that would require it to be able to automatically detect which a device is plugged in, and which devices are compatible.

I can write a wrapper script to do that myself, unfortunately my C skills aren't good enough to add it to this code base, and it would be better if the daemon didn't rely on a third-party python script.

**Comment by nsensfel** [comment]
Hello,

I do not believe having relabsd run as a daemon waiting for the actual device to be plugged in is a good solution (especially since I would expect this to limit the software's portability). I am not sure this is what you meant, though.
I agree that relabsd should be made into a proper daemon, I'll look into it next week. You'd then be able to run relabsd as a "client" that sends commands to its "server" process(es), much like the "mocp" music player behaves.
This should actually let you automatically start relabsd when the device is plugged in, using the system's device manager to run whatever command you need (as shown in https://unix.stackexchange.com/questions/65891/how-to-execute-a-shellscript-when-i-plug-in-a-usb-device ).

**Comment by nsensfel** [comment]
It's taking longer than I expected (mostly because I kind of got lost in a book I was reading). As of https://github.com/nsensfel/relabsd/commit/8e624e9919040e2ec99be764394bb33a2bc77fd9, you should be able to get something close to what you wanted. In addition, I've rewrote most of the program, which fixed a few issues (like relabsd not closing instantly upon receiving a `SIGINT` or `SIGTERM`) and incorporated the timeout functionality.

### Still missing: ###
Before I can actually merge this branch with `master`, I still have to fully implement sending command from the client to the server, which should let users modify virtual devices on the fly as well as closing them without having to sending `SIGTERM` or `SIGINT` to the server process.
At the moment, you can send commands to the server using clients, but the server simply discards them.

### relabsd plug & play: ###
I don't have udev on my machine, so I've not been able to test it (I'll set it up on a virtual machine to test things out when I find the time), but the link I gave in my previous comment should let you run a shell script upon the physical device being plugged in.
I don't know what privileges this script is run with, and that may very well be a problem, but other than that, you should be able to write a device specific rule and script that runs the following command:
`relabsd -1 /dev/input/event_given_by_udev -d -f your_config_file`
The `-d` makes it a daemon (although the standard input and outputs are not yet set to `/dev/null`, which shouldn't matter anyway).
I have not yet looked into how to retrieve the correct `/dev/input/event_given_by_udev`, but I assume udev will be nice enough to provide it.
Unplugging the device should (gracefully) crash relabsd.
As mentioned in the section above, the client/server functionality is not yet fully implemented, so I would recommend figuring out exactly what configuration you want for your device before making it work as a plug and play. In the future, the plug and play relabsd instance is intended to create a server communication file, which will let you modify it on the fly.

### Compatible devices: ###
Running `relabsd -? /dev/input/whatever` will print the name of the device and its relative axes. You can add options after that to test a configuration with that input device.
In this mode, the program returns:
- 2 if the device has relative axes and the requested virtual device configuration is compatible.
- 1 if the device has relative axes and the configuration is not compatible.
- 0 if the device has no relative axes (not compatible).
- -1 on error.

This should let you create whatever virtual device manager you want. I don't know if there is a (POSIX, not just Linux) way of getting a list of all input devices so that I could simply test them all and show the compatible ones, I might look into it after this branch is merged.

**Comment by traverseda** [comment]
Awesome, I'll try to get an archlinux package up and running soon. This does seem to be a much better approach than the standard spacenavigator daemon.

**Comment by nsensfel** [comment]
https://github.com/nsensfel/relabsd/commit/87a86b9a599de35d09da7d954ba662091accc90b has working client/server commands.
I've merged the branch into `master`.

#### Soonish future work: ####
-  Cleanup pass, as there are some error tests that still need printing and a few coding style inconsistencies.
- Client side feedback for the commands sent to the server, including having the program return specific values upon success and failure.
- Link standard input/outputs to `/dev/null` when running as a daemon.
- Document the new features in the Wiki.

#### Probably not very soon future work: ####
- Provide a template for the (e)udev script that lets you make it plug and play. If you figure it out, I'd greatly appreciate if you could share it so that I don't have to set up a VM.
- Have `relabsd -?` test all devices found in the sub-folders of `/dev/input` for compatibility.

**Comment by traverseda** [comment]
> Provide a template for the (e)udev script that lets you make it plug and play. If you figure it out, I'd greatly appreciate if you could share it so that I don't have to set up a VM.

If I don't get it done in the next couple of weeks, bug me about it.

**Comment by NXTler** [comment]
Hey, has anyone figured out how to have plug & play on a udev machine?
